### ISSUE TITLE
Multiple versions is not handled and causes errors

### ISSUE THREAD

**Issue by Ebsan** [LOLINTERNETZ/vscodeoffline#19]
Attempting to `--sync` or `--syncall` causes unrecoverable errors when multiple versions are returned. Looks like there's already a PR (https://github.com/LOLINTERNETZ/vscodeoffline/pull/17) to try to solve this by returning an empty array in the `_get_asset_types()` method, but I'm also getting errors in the `version()` method.

```
2021-10-20T19:33:36.254545000Z [W 211020 19:33:36 sync:178] version(). More than one version returned for actboy168.lua-debug. Unhandled.
2021-10-20T19:33:36.257052000Z Traceback (most recent call last):
2021-10-20T19:33:36.257387000Z   File "/opt/vscoffline/sync.py", line 577, in <module>
2021-10-20T19:33:36.257670000Z     bonus = extensions[identity].process_embedded_extensions(config.artifactdir_extensions, mp) + bonus
2021-10-20T19:33:36.257923000Z   File "/opt/vscoffline/sync.py", line 156, in process_embedded_extensions
2021-10-20T19:33:36.258211000Z     manifestpath = os.path.join(destination, self.identity, self.version(), 'Microsoft.VisualStudio.Code.Manifest')
2021-10-20T19:33:36.258461000Z   File "/usr/local/lib/python3.7/posixpath.py", line 94, in join
2021-10-20T19:33:36.258729000Z     genericpath._check_arg_types('join', a, *p)
2021-10-20T19:33:36.258980000Z   File "/usr/local/lib/python3.7/genericpath.py", line 153, in _check_arg_types
2021-10-20T19:33:36.259212000Z     (funcname, s.__class__.__name__)) from None
2021-10-20T19:33:36.259474000Z TypeError: join() argument must be str or bytes, not 'NoneType'
```

**Comment by forky2** [comment]
I've started looking at this version problem.

**Comment by forky2** [comment]
Currently testing the above fix. So far it has successfully worked for actboy168.lua-debug showing it works in principle, but I'm going to let it run overnight for * before I finish tidying it up and submitting a PR.
