### ISSUE TITLE
More than one version returned

### ISSUE THREAD

**Issue by ttutko** [LOLINTERNETZ/vscodeoffline#5]
I don't know if the marketplace api changed or not but all of a sudden I'm getting errors related to multiple versions being returned both before and after updating to latest version. 

The output looks like this over and over for each extension:

> vscsync_1     | [W 191216 14:33:56 sync:173] version(). More than one version returned for alexdima.vscode-lcov. Unhandled.    
vscsync_1     | [I 191216 14:33:56 sync:554] <VSCExtensionDefinition> Target: alexdima.vscode-lcov Id: 2232b887-1a89-4297-9ae1-0155ef258ab1 Version: None

Which ultimately ends up getting to this:

> vscsync_1     | [I 191216 14:33:56 sync:562] Checking and Downloading Updates for 15122 Extensions
vscsync_1     | [I 191216 14:33:56 sync:567] Progress 0/15122 (0.0%)
vscsync_1     | [W 191216 14:33:56 sync:200] _get_asset_types(). More than one version returned for ms-python.python. Unhandled.
vscsync_1     | Traceback (most recent call last):
vscsync_1     |   File "/opt/vscoffline/sync.py", line 568, in <module>
vscsync_1     |     extensions[identity].download_assets(config.artifactdir_extensions)
vscsync_1     |   File "/opt/vscoffline/sync.py", line 147, in download_assets
vscsync_1     |     for availableasset in availableassets:
vscsync_1     | TypeError: 'NoneType' object is not iterable
vscodeoffline_vscsync_1 exited with code 1

**Comment by ttutko** [comment]
After pulling the latest and forcing a rebuild of my container locally this seems to have resolved itself. I don't know exactly what lead to this at the moment but I don't think it's a code issue so I'm going to close this.
