### ISSUE TITLE
 vscsync doesn't work

### ISSUE THREAD

**Issue by dan83g** [LOLINTERNETZ/vscodeoffline#59]
It looks like Microsoft has turned on some kind of protection. 
```
Traceback (most recent call last):
  File "sync.py", line 745, in <module>
    config.artifactdir_installers)
  File "sync.py", line 124, in download_update
    self.updateurl, allow_redirects=True, timeout=vsc.TIMEOUT)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='az764295.vo.msecnd.net', port=443): Max retries exceeded with url: /stable/a6606b6ca720bca780c2d3c9d4cc3966ff2eca12/VSCodeSetup-ia32-1.83.1.exe (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd49ec90e90>, 'Connection to az764295.vo.msecnd.net timed out. (connect timeout=12)'))
```
https://az764295.vo.msecnd.net/stable/a6606b6ca720bca780c2d3c9d4cc3966ff2eca12/VSCodeSetup-ia32-1.83.1.exe
But it downloads well through the browser.

**Comment by SpeedySpeedBoii** [comment]
Happened to me as well after using this script for a couple of days. Is it permenant?

**Comment by LOLINTERNETZ** [comment]
I'm not sure what would be happening here. I suspect it's some kind of local DNS issue. Perhaps the dns resolves to your vscgallery host?
