### ISSUE TITLE
FileNotFoundError while running vscsync

### ISSUE THREAD

**Issue by liroyc14** [LOLINTERNETZ/vscodeoffline#9]
Getting the following error while running:
```
docker-compose up vscsync
```

```
vscsync_1     | [I 201007 07:53:16 sync:567] Progress 0/580 (0.0%)
vscsync_1     | Traceback (most recent call last):
vscsync_1     |   File "/opt/vscoffline/sync.py", line 568, in <module>
vscsync_1     |     extensions[identity].download_assets(config.artifactdir_extensions)
vscsync_1     |   File "/opt/vscoffline/sync.py", line 148, in download_assets
vscsync_1     |     self._download_asset(destination, availableasset)        
vscsync_1     |   File "/opt/vscoffline/sync.py", line 199, in _download_asset
vscsync_1     |     with open(destfile, 'wb') as dest:
vscsync_1     | FileNotFoundError: [Errno 2] No such file or directory: '/artifacts/extensions/vscodevim.vim/1.17.1/Microsoft.VisualStudio.Code.WebResources/extension/CHANGELOG.md'
vscodeoffline_vscsync_1 exited with code 1
```

**Comment by assafushy** [comment]
+1

when are you going to merge the pr?
